import type { FullBand, RenderState } from './search'

// docs/analysis/010-screens/outputs/chips.json — generated by build_chips.py,
// never hand-typed here. Every chip's `expect` was read off the live RPC in a
// rolled-back transaction; re-run the script rather than editing the file.
//
// CRITICAL: components choose their state off `expect.render_state`, never off
// `expect.band`. They deliberately disagree — `escape room` GB·Birmingham is
// band=confident but render_state=near_empty, because near_empty overrides its
// band (010-screens/SPEC.md decision 15). `roles` groups/labels the chip row
// for the demo script; it is not a rendering input.
export interface ChipExpectation {
  render_state: RenderState
  band: FullBand | 'unknown_query' | 'empty'
  near_empty: boolean
  // Added with the city_empty state (010-screens/SPEC.md amendment) and the
  // #17 structural fix — mirrors FullSearchResult's own fields exactly, not
  // re-derived here either.
  city_empty?: boolean
  demand_row_written?: boolean
  available: number
  result_count: number
  normalised: boolean
  resolved_to: string | null
  alternatives_above_floor: boolean
  alt_max: number | null
  part_a_logged_here: boolean
  part_a_class: string | null
  part_a_coverage: 'stocked' | 'absent' | 'plausible' | null
  band_agrees_with_part_a: boolean | null
}

export interface Chip {
  id: string
  market: string
  city: string
  query: string
  roles: string[]
  expect: ChipExpectation
}

export interface ChipsFixture {
  generated_by: string
  generated_on: string
  chips: Chip[]
}
