import { createClient } from '@supabase/supabase-js'

// One client, created once, imported everywhere. No ad-hoc createClient in
// components or stores.
//
// Deliberately UNTYPED for now. The usual `createClient<Database>` needs
// src/types/database.types.ts, generated by `supabase gen types typescript --local`,
// and there is no schema yet to generate it from. Generating an empty type would be
// worse than none: it would type-check queries against tables that do not exist.
// The generic gets added in the same unit that adds the first migration.

const url = import.meta.env.VITE_SUPABASE_URL
const publishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY

if (!url || !publishableKey) {
  throw new Error(
    'Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
      'Copy web/app/.env.local from .env.example and fill it from `npx supabase status`.',
  )
}

// Publishable key, not the legacy anon key — Supabase treats anon keys as
// compatibility-only (005-stack-init decision F). The secret / service_role key
// must never reach this file: anything imported here ships in the browser bundle.
export const supabase = createClient(url, publishableKey)

export const supabaseUrl = url
