#!/usr/bin/env python3
"""WCAG 2.1 contrast ratios for the colour pairs quoted in DESIGN-SYSTEM.md §2.

Reads hex values out of outputs/tokens.json — generated by extract_tokens.py — so
no colour is retyped here, only named. Re-run this before quoting any ratio.

  python3 docs/design/contrast_check.py
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
TOKENS = HERE / "outputs" / "tokens.json"

# (foreground token, background token or literal hex, what it is used for)
PAIRS = [
    ("--text-color-body", "--background-color-body", "body text on white"),
    ("--color-primary", "--background-color-body", "primary green on white"),
    ("--background-color-body", "--color-primary", "white on primary green"),
    ("--text-color-extra-price", "--background-color-body", "promo-code price on white"),
    ("--text-color-danger", "--background-color-body", "danger text on white"),
    ("--color-green-700", "--color-green-100", "discount badge fg on badge bg"),
    ("--color-green-600", "--background-color-body", "sale price (green-600) on white"),
    ("--color-green-500", "--background-color-body", "green-500 on white"),
    ("--text-color-hyperlink", "--background-color-body", "link on white"),
    ("--text-color-muted", "--background-color-body", "muted metadata on white"),
    ("--text-color-tertiary", "--background-color-body", "tertiary on white"),
    ("--color-warning", "--background-color-body", "warning on white"),
    ("--color-success", "--background-color-body", "success/teal on white"),
    ("--color-teal-700", "--background-color-body", "teal-700 on white"),
    ("--color-extra", "--background-color-extra-subtle", "adjacency fg on adjacency bg"),
    ("--color-teal-700", "--background-color-success-subtle", "teal-700 on demand-row bg"),
    ("--color-teal-800", "--background-color-success-subtle", "demand-row fg on its bg"),
    ("--text-color-body", "--background-color-secondary", "body on muted surface"),
    ("--text-color-light", "--background-color-dark", "staff panel body text"),
    ("--color-neutral-300", "--background-color-dark", "staff panel muted text"),
]


def luminance(hex_value):
    h = hex_value.lstrip("#")
    channels = [int(h[i : i + 2], 16) / 255 for i in (0, 2, 4)]
    lin = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def ratio(fg, bg):
    hi, lo = sorted((luminance(fg), luminance(bg)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def verdict(r):
    if r >= 7:
        return "AAA"
    if r >= 4.5:
        return "AA"
    if r >= 3:
        return "AA large / non-text only"
    return "FAILS"


def main():
    if not TOKENS.exists():
        sys.exit("run extract_tokens.py first — outputs/tokens.json is missing")
    tokens = json.loads(TOKENS.read_text())

    def hex_of(name):
        if name.startswith("#"):
            return name
        entry = tokens.get(name)
        if not entry or "hex" not in entry:
            sys.exit(f"{name} is not a colour token in outputs/tokens.json")
        return entry["hex"]

    print(f"{'ratio':>6}  {'verdict':<24}  pair")
    for fg, bg, label in PAIRS:
        f, b = hex_of(fg), hex_of(bg)
        r = ratio(f, b)
        print(f"{r:>6.2f}  {verdict(r):<24}  {label}  ({f} on {b})")


if __name__ == "__main__":
    main()
